name: cd

on:
    push:
        branches: [main]

jobs:
    deploy:
        name: Deploy
        runs-on:  ubuntu-latest
        timeout-minutes: 10

       #env:
        # DATABASE_URL: ${{secrets.DATABASE_URL}}

        steps:
            - name: Check out code
              uses: actions/checkout@v4

            - name: Set up Go
              uses: actions/setup-go@v5
              with:
                go-version: '1.23.0'
            
            - name: Build app
              run: . scripts/buildprod.sh

            #Set up google cloud sdk

            #Build and push docker image to gcloud

            #ssh to server
            - name: executing remote ssh commands using private key
              uses: appleboy/ssh-action@v1.1.0
              with:
                host: ${{ secrets.HOST }}
                username: ${{ secrets.USERNAME }}
                key: ${{ secrets.SSH_PRIVATE_KEY }}
                port: ${{ secrets.PORT }}
                script: whoami

            #pull new image

            #switch containers