name: cd

on:
    push:
        branches: [main]

jobs:
    deploy:
        name: Deploy
        runs-on:  ubuntu-latest
        timeout-minutes: 10

       #env:
        # DATABASE_URL: ${{secrets.DATABASE_URL}}

        steps:
            - name: Check out code
              uses: actions/checkout@v4

            - name: Set up Go
              uses: actions/setup-go@v5
              with:
                go-version: '1.23.0'
            
            - name: Build app
              run: . scripts/buildprod.sh
            
            - name: Check that app is built
              run: echo ${PWD} && ls -lR

            #TODO: set up gcp instead of docker hub
              #Set up google cloud sdk
              #Build and push docker image to gcloud

            #Build and push docker image to docker hub
            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3
            
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3
            
            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}
            
            - name: Build and push image
              uses: docker/build-push-action@v6
              with:
                push: true
                tags: user/app:latest

            #ssh to server, pull image, stop container, start new container
            - name: executing remote ssh commands using private key
              uses: appleboy/ssh-action@v1.1.0
              with:
                host: ${{ secrets.HOST }}
                username: ${{ secrets.USERNAME }}
                key: ${{ secrets.SSH_PRIVATE_KEY }}
                port: ${{ secrets.PORT }}
                script: |
                  echo "hello_world"
                  docker pull theorm626/personal-website:latest
                  docker stop personal-website
                  docker rm personal-website
                  docker run -d --network=webapps --name personal-server -p 8080:8080 theorm626/personal-website:latest